name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git tools
        run: |
          sudo apt-get update && sudo apt-get install -y git-lfs
          git lfs install
          pip install git-filter-repo

      - name: Cleanup zip files from history
        run: |
          # Xóa tất cả file zip ra khỏi lịch sử Git
          git filter-repo --path-glob "*.zip" --invert-paths || true

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote remove space || true
          git remote add space https://thaiquangvinh:$HF_TOKEN@huggingface.co/spaces/thaiquangvinh/dem302
          
          # Force push repo sạch sang Hugging Face
          git push space main --force
